export const BACKGROUND_STORE_NAME = 'background'
export const MAIN_STORE_NAME = 'main'
export const PLAYER_STORE_NAME = 'player'
export const LEGACY_STORE_KEY = 'reyohoho.store'
export const LEGACY_STORE_KEY_BACKUP = 'vuex_backup'
export const AUTH_STORE_NAME = 'auth'
export const API_STORE_NAME = 'api'
